---
- name: Desplegar Secrets
  kubernetes.core.k8s:
    state: present
    src: ../../k8s/secret.yaml

- name: Desplegar PVC de la base de datos
  kubernetes.core.k8s:
    state: present
    src: ../../k8s/db-pvc.yaml

- name: Desplegar Base de Datos
  kubernetes.core.k8s:
    state: present
    src: ../../k8s/db-deployment.yaml

- name: Desplegar Servicio de Base de Datos
  kubernetes.core.k8s:
    state: present
    src: ../../k8s/db-service.yaml

- name: Desplegar Backend
  kubernetes.core.k8s:
    state: present
    src: ../../k8s/backend-deployment.yaml

- name: Desplegar Servicio de Backend
  kubernetes.core.k8s:
    state: present
    src: ../../k8s/backend-service.yaml

- name: Desplegar Frontend
  kubernetes.core.k8s:
    state: present
    src: ../../k8s/frontend-deployment.yaml

- name: Desplegar Servicio de Frontend
  kubernetes.core.k8s:
    state: present
    src: ../../k8s/frontend-service.yaml

- name: Desplegar Ingress Controller
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

- name: Esperar a que el Ingress esté listo
  command: >
    kubectl wait --namespace ingress-nginx
    --for=condition=ready pod
    --selector=app.kubernetes.io/component=controller
    --timeout=300s

- name: Desplegar reglas de Ingress
  kubernetes.core.k8s:
    state: present
    src: ../../k8s/ingress.yaml

- name: Desplegar Autoescalado (HPA)
  kubernetes.core.k8s:
    state: present
    src: ../../k8s/hpa.yaml

