apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # "rootpassword" en Base64
  mysql-database: dGVzdGRi               # "testdb" en Base64
